# Generated by Django 2.1.5 on 2019-02-06 15:39

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('startTime', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(0, 3600))),
                ('reserved', models.BooleanField(default=False)),
                ('barbery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='mainapp.Barbery')),
            ],
        ),
    ]
