# Generated by Django 2.1.5 on 2019-02-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbery',
            old_name='user',
            new_name='barber',
        ),
    ]
