# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbery',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='barbery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='mainapp.Barbery'),
        ),
    ]
