# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190225_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbery',
            name='address',
            field=models.CharField(max_length=1000, unique=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='barbery',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='barbery',
            name='name',
            field=models.CharField(max_length=100, verbose_name="barbery's name"),
        ),
        migrations.AlterField(
            model_name='barbery',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='slug for url'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 3600), verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='reserved',
            field=models.BooleanField(default=False, verbose_name='is reserved'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
    ]
