# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 12:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190225_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbery',
            options={'ordering': ['name'], 'verbose_name': 'Barbery', 'verbose_name_plural': 'Barberies'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['slot'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['-start_time'], 'verbose_name': 'Time slot', 'verbose_name_plural': 'Time slots'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['username'], 'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
        migrations.AlterField(
            model_name='barbery',
            name='address',
            field=models.CharField(max_length=1000, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='barbery',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='barbery',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Barbery's name"),
        ),
        migrations.AlterField(
            model_name='barbery',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='Slug for url'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 3600), verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='reserved',
            field=models.BooleanField(default=False, verbose_name='Is reserved'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
