# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-24 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190303_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='barbery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='mainapp.Barbery', verbose_name='barbery'),
        ),
    ]
